# Generated by Django 5.1.1 on 2024-10-31 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(choices=[('RGB', 'RGB'), ('HEX', 'HEX'), ('HSL', 'HSL'), ('CMYK', 'CMYK'), ('HSV', 'HSV'), ('LAB', 'LAB')], max_length=50)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('cover_image_alt', models.CharField(default='Color Convertor in PixelOpen.COM For Free', max_length=200)),
                ('related_post', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_response', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConverterTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converterName', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('cover_image_alt', models.CharField(default='Color Convertor in PixelOpen.COM For Free', max_length=200)),
                ('related_post', models.CharField(blank=True, max_length=1000, null=True)),
                ('change_slut', models.SlugField(blank=True, null=True, unique=True)),
                ('input_category', models.CharField(choices=[('RGB', 'RGB'), ('HEX', 'HEX'), ('HSL', 'HSL'), ('CMYK', 'CMYK'), ('HSV', 'HSV'), ('LAB', 'LAB')], max_length=50)),
                ('output_category', models.CharField(choices=[('RGB', 'RGB'), ('HEX', 'HEX'), ('HSL', 'HSL'), ('CMYK', 'CMYK'), ('HSV', 'HSV'), ('LAB', 'LAB')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FullFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=100)),
                ('feature_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('cover_image_alt', models.CharField(default='White Logo in PixelOpen.COM For Free', max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('post_category', models.CharField(blank=True, max_length=100, null=True)),
                ('post_author', models.CharField(default='PixelOpen Team', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('long_description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('cover_image_alt', models.CharField(default='White Logo in PixelOpen.COM For Free', max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('one_click_purchasing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
