# Generated by Django 5.1.1 on 2024-11-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('period', models.IntegerField()),
            ],
        ),
    ]
