# Generated by Django 5.1.1 on 2024-11-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
