# Generated by Django 5.1.1 on 2024-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderhistory_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=100)),
                ('initial_img', models.CharField(max_length=500)),
                ('svg_content', models.TextField()),
                ('is_download', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
